# Generated by Django 3.1 on 2020-12-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='ФИО')),
                ('qualification', models.CharField(max_length=80, null=True, verbose_name='Квалификация')),
                ('organization', models.CharField(max_length=100, verbose_name='Организация')),
                ('review', models.TextField(verbose_name='Отзыв')),
                ('active', models.BooleanField(default=False, verbose_name='Активный')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
                'ordering': ('created',),
            },
        ),
    ]
