# Generated by Django 3.1.4 on 2020-12-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201228_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/projects', verbose_name='Фото'),
        ),
    ]
